start-dependencies.sh: fix SSL passthrough ordering, speedups
Make sure we patch NGinx to allow SSL Passthrough for Strimzi
*after* ingress-nginx is installed. If we are installing the
Helm chart, enable passthrough when we install with Helm.

Disable leader election when we install cert-manager and
ingress-nginx for a big speedup.

If we are installing ingress-nginx, set it to use a NodePort
(shudder) for the service instead of a LoadBalancer since
kind doesn't install a LoadBalancer by default.

Remove --wait for cert-manager since we don't seem to need it.

And lastly, the reason why I was here tweaking things: make
sure that ingress-nginx is ready (we can defer this until near
the end) so we can avoid errors like this when installing
Horizon in CI:

Error: INSTALLATION FAILED: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": failed to call webhook: Post "https://ingress-nginx-controller-admission.ingress-nginx.svc:443/networking/v1/ingresses?timeout=10s": dial tcp 10.96.55.161:443: connect: connection refused